using System;
using System.Buffers.Binary;
using System.Text;

namespace SlopArena.Shared
{
    /// <summary>
    /// Pre-baked bone positions for one animation.
    /// Loaded from a .bin file generated by the BakeSkeleton tool.
    /// No Godot dependency — usable on server and client.
    /// </summary>
    public class BakedAnimationData
    {
        public string[] BoneNames = null!;
        public BakedAnim[] Animations = null!;

        /// <summary>
        /// One baked animation.
        /// </summary>
        public class BakedAnim
        {
            public string Name = null!;
            public int FrameCount;
            /// <summary>positions[frame][boneIndex * 3 + 0/1/2] = x/y/z</summary>
            public float[][] Frames = null!; // [frameCount][boneCount * 3]
        }

        /// <summary>
        /// Load baked data from .bin format.
        /// </summary>
        public static BakedAnimationData LoadFromBin(byte[] data)
        {
            int pos = 0;

            // Magic
            uint magic = BinaryPrimitives.ReadUInt32LittleEndian(data.AsSpan(pos)); pos += 4;
            if (magic != 0x4C454B53) // "SKEL"
                throw new Exception("Not a valid baked skeleton file");

            uint version = BinaryPrimitives.ReadUInt32LittleEndian(data.AsSpan(pos)); pos += 4;
            if (version != 1)
                throw new Exception($"Unknown version: {version}");

            uint boneCount = BinaryPrimitives.ReadUInt32LittleEndian(data.AsSpan(pos)); pos += 4;
            uint animCount = BinaryPrimitives.ReadUInt32LittleEndian(data.AsSpan(pos)); pos += 4;

            // Bone names
            var boneNames = new string[boneCount];
            for (int i = 0; i < boneCount; i++)
            {
                uint nameLen = BinaryPrimitives.ReadUInt32LittleEndian(data.AsSpan(pos)); pos += 4;
                boneNames[i] = Encoding.UTF8.GetString(data, pos, (int)nameLen);
                pos += (int)nameLen;
            }

            // Animations
            var anims = new BakedAnim[animCount];
            for (int a = 0; a < animCount; a++)
            {
                uint nameLen = BinaryPrimitives.ReadUInt32LittleEndian(data.AsSpan(pos)); pos += 4;
                string animName = Encoding.UTF8.GetString(data, pos, (int)nameLen);
                pos += (int)nameLen;

                uint frameCount32 = BinaryPrimitives.ReadUInt32LittleEndian(data.AsSpan(pos)); pos += 4;
                int frameCount = (int)frameCount32;

                int stride = (int)boneCount * 3;
                var frames = new float[frameCount][];
                for (int f = 0; f < frameCount; f++)
                {
                    var frame = new float[stride];
                    for (int s = 0; s < stride; s++)
                    {
                        frame[s] = BitConverter.Int32BitsToSingle(BinaryPrimitives.ReadInt32LittleEndian(data.AsSpan(pos)));
                        pos += 4;
                    }
                    frames[f] = frame;
                }

                anims[a] = new BakedAnim
                {
                    Name = animName,
                    FrameCount = frameCount,
                    Frames = frames,
                };
            }

            return new BakedAnimationData
            {
                BoneNames = boneNames,
                Animations = anims,
            };
        }

        /// <summary>
        /// Get the local-space position of a bone at a specific animation frame.
        /// Returns true if found. Positions are (x, y, z).
        /// </summary>
        public bool GetBonePosition(string animName, int frameIndex, int boneDefIndex, out float x, out float y, out float z)
        {
            x = y = z = 0;

            // Find animation
            for (int a = 0; a < Animations.Length; a++)
            {
                if (Animations[a].Name == animName)
                {
                    int fc = Animations[a].FrameCount;
                    if (frameIndex < 0) frameIndex = 0;
                    if (frameIndex >= fc) frameIndex = fc - 1;

                    int stride = BoneNames.Length * 3;
                    int baseIdx = boneDefIndex * 3;
                    if (baseIdx + 2 < stride)
                    {
                        x = Animations[a].Frames[frameIndex][baseIdx];
                        y = Animations[a].Frames[frameIndex][baseIdx + 1];
                        z = Animations[a].Frames[frameIndex][baseIdx + 2];
                        return true;
                    }
                    return false;
                }
            }
            return false;
        }

        /// <summary>
        /// Returns the minimum Y across all bones at frame 0 of the "idle" animation.
        /// Negative = feet/toes below Hips. Used to compute HipHeight for character defs.
        /// Returns 0 if idle animation is not found.
        /// </summary>
        public float GetMinBoneY()
        {
            for (int a = 0; a < Animations.Length; a++)
            {
                if (Animations[a].Name == "idle")
                {
                    int stride = BoneNames.Length * 3;
                    float minY = float.MaxValue;
                    for (int b = 0; b < BoneNames.Length; b++)
                    {
                        float y = Animations[a].Frames[0][b * 3 + 1];
                        if (y < minY) minY = y;
                    }
                    return minY;
                }
            }
            return 0f;
        }

        /// <summary>
        /// Find animation index by name, or -1.
        /// </summary>
        public int FindAnimIndex(string name)
        {
            for (int i = 0; i < Animations.Length; i++)
                if (Animations[i].Name == name)
                    return i;
            return -1;
        }
    }
}
