#nullable enable
using System.Text;
using System.Text.Json;
using System.Text.Encodings.Web;

namespace SlopArena.MoveDataReport;

internal static class ContactCoverageHtml
{
    internal static string ToHtml(ContactCoverageReport.CoverageReportData report)
    {
        string json = JsonSerializer.Serialize(report, new JsonSerializerOptions
        {
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            Encoder = JavaScriptEncoder.Default,
            WriteIndented = false,
        });
        var sb = new StringBuilder(32_000);
        sb.Append("""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SlopArena contact coverage</title><style>""");
        sb.Append("""body{font:14px system-ui,sans-serif;margin:20px;color:#18202a}h1{font-size:22px;margin:0 0 6px}h2{font-size:17px;margin:24px 0 8px;border-bottom:1px solid #ccd3db;padding-bottom:4px}.meta{color:#46515d;line-height:1.45;max-width:1100px}.controls{display:flex;flex-wrap:wrap;gap:10px;margin:16px 0}.controls label{display:flex;gap:5px;align-items:center;font-weight:600}.controls select{font:inherit;padding:4px}.panels{display:flex;gap:14px;flex-wrap:wrap}.panel{border:1px solid #c9d1d9;border-radius:5px;padding:8px;background:#fbfcfd}.panel h3{font-size:14px;margin:0 0 5px}.map{display:grid;grid-template-columns:28px auto;grid-template-rows:auto 24px;align-items:center}.axis-y{writing-mode:vertical-rl;transform:rotate(180deg);text-align:center;font-size:11px}.axis-x{text-align:center;font-size:11px}.grid{display:grid;border:1px solid #8995a1}.cell{width:18px;height:18px;border:0;border-right:1px solid #fff;border-bottom:1px solid #fff;padding:0;font-size:10px;cursor:pointer}.cell:focus{outline:2px solid #111;z-index:1}.hit{background:#4caf70;color:#061c0d}.miss{background:#e7ebef;color:#52606d}.unavailable{background:#f6c56c;color:#402800}.truncated{background:#cf8de0;color:#280034}.diff-both-hit{background:#4caf70}.diff-both-miss{background:#e7ebef}.diff-gained{background:#8be0a5}.diff-lost{background:#f2a0a7}.diff-not-comparable{background:#aab3bc}.legend{display:flex;gap:9px;flex-wrap:wrap;margin:7px 0;color:#4b5661;font-size:12px}.legend span:before{content:'';display:inline-block;width:11px;height:11px;margin-right:3px;vertical-align:-1px;background:#e7ebef}.legend .lh:before{background:#4caf70}.legend .lu:before{background:#f6c56c}.legend .lt:before{background:#cf8de0}.legend .lg:before{background:#8be0a5}.legend .ll:before{background:#f2a0a7}.detail{min-height:110px;border:1px solid #c9d1d9;padding:8px;background:#f8fafc;white-space:pre-wrap;font-family:ui-monospace,monospace;font-size:12px}.timing table,.summary{border-collapse:collapse;font-size:12px}.timing td,.timing th,.summary td,.summary th{border:1px solid #c9d1d9;padding:3px 6px;text-align:left}.timing th,.summary th{background:#eef2f6}.interval{font-family:ui-monospace,monospace}.small{font-size:12px;color:#596672}</style></head><body>""");
        sb.Append("""<h1>Actual contact coverage</h1><div id="meta" class="meta"></div><div class="controls"><label>Attacker <select id="attacker"></select></label><label>Move <select id="move"></select></label><label>Scenario <select id="scenario"></select></label></div><div class="legend"><span class="lh">hit</span><span>miss</span><span class="lu">unavailable</span><span class="lt">truncated</span><span class="lg">gained</span><span class="ll">lost</span><span>diff panel is paired baseline/candidate</span></div><div id="panels" class="panels"></div><h2>Selected cell</h2><div id="detail" class="detail">Select a cell with pointer or keyboard.</div><div id="timing"></div><h2>Factual move summary</h2><div id="summary"></div><script id="coverage-data" type="application/json">""");
        sb.Append(json);
        sb.Append("""</script><script>""");
        sb.Append("""
const data=JSON.parse(document.getElementById('coverage-data').textContent);
const att=document.getElementById('attacker'),move=document.getElementById('move'),scenario=document.getElementById('scenario');
const panels=document.getElementById('panels'),detail=document.getElementById('detail'),timing=document.getElementById('timing'),summary=document.getElementById('summary');
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const state=s=>s?`pos=(${s.positionX.toFixed(2)},${s.positionY.toFixed(2)},${s.positionZ.toFixed(2)}) centerY=${s.capsuleCenterY.toFixed(2)} vel=(${s.velocityX.toFixed(2)},${s.velocityY.toFixed(2)},${s.velocityZ.toFixed(2)}) ground=${s.isGrounded} state=${s.actionState} facing=${s.facingYawDegrees.toFixed(1)}°`:'none';
function opt(sel,items,label){sel.innerHTML=items.map((x,i)=>`<option value="${i}">${esc(label(x))}</option>`).join('');}
function moves(){return data.moves.filter(x=>x.attacker===att.value)}
function currentMove(){return moves()[+move.value]||moves()[0]}
function currentMap(){return currentMove()?.maps.find(x=>x.scenarioId===scenario.value)}
function smp(c,p){return p==='baseline'?c.baseline:c.candidate}
function draw(title,cells,kind,cols){const p=document.createElement('div');p.className='panel';p.innerHTML=`<h3>${title}</h3>`;const w=document.createElement('div');w.className='map';const y=document.createElement('div');y.className='axis-y';y.textContent='+Z forward';const g=document.createElement('div');g.className='grid';g.style.gridTemplateColumns=`repeat(${cols},18px)`;cells.forEach(c=>{const b=document.createElement('button');b.className='cell '+(kind==='diff'?'diff-'+c.comparison:smp(c,kind).outcome);b.tabIndex=0;b.title=`X ${c.relativeX}, Z ${c.relativeZ}`;b.textContent=kind==='diff'?({'both-hit':'H','both-miss':'·',gained:'+ ',lost:'- ','not-comparable':'?'}[c.comparison]||'?'):(smp(c,kind).outcome==='hit'?'H':smp(c,kind).outcome==='miss'?'·':smp(c,kind).outcome==='unavailable'?'U':'T');b.onclick=()=>show(c);g.appendChild(b)});const x=document.createElement('div');x.className='axis-x';x.textContent=`−X left · +X right (step ${data.grid.step}m)`;w.append(y,g,x);p.append(w);return p}
function show(c){const b=c.baseline,ca=c.candidate;detail.textContent=`cell victim relative X/Z=(${c.relativeX},${c.relativeZ}) comparison=${c.comparison}\nBASELINE ${b.outcome} ${b.reason||'—'} activation=${b.activationTick??'—'} facing=${b.activationFacingYawDegrees?.toFixed(1)??'—'}° contact=${b.firstContact?.tick??'—'} damage=${b.firstContact?.damage?.toFixed(2)??'—'}\n  attacker: ${state(b.prePressAttacker)}\n  victim: ${state(b.prePressVictim)}\nCANDIDATE ${ca.outcome} ${ca.reason||'—'} activation=${ca.activationTick??'—'} facing=${ca.activationFacingYawDegrees?.toFixed(1)??'—'}° contact=${ca.firstContact?.tick??'—'} damage=${ca.firstContact?.damage?.toFixed(2)??'—'}\n  attacker: ${state(ca.prePressAttacker)}\n  victim: ${state(ca.prePressVictim)}\nNOTE: SpellResolver.HitResult has no authored hit index.`}
function intervals(a){return a.length?a.map(x=>`[${x.startPressTick},${x.endPressTick}] ${x.successfulPressTicks} hits, longest ${x.longestContiguousTicks}, ${x.nominalMilliseconds.toFixed(1)}ms, ${x.boundaryClipped?'boundary-clipped':'not clipped'}`).join('; '):'none'}
function renderTiming(m){if(!m.timing.length){timing.innerHTML='<h2>Timing windows</h2><div class=\"small\">Passive scenarios intentionally have no timing sweep.</div>';return}const t=m.timing.find(x=>x.scenarioId===scenario.value);if(!t){timing.innerHTML='';return}timing.innerHTML='<h2>Discrete timing windows</h2><div class=\"small\">Nominal milliseconds = successful tick count × 1000 / 60. Not a reaction-time recommendation.</div><table><tr><th>lane</th><th>baseline</th><th>candidate</th></tr>'+t.lanes.map(x=>`<tr><td>(${x.relativeX},${x.relativeZ})</td><td class=\"interval\">${esc(intervals(x.baselineIntervals))}</td><td class=\"interval\">${esc(intervals(x.candidateIntervals))}</td></tr>`).join('')+'</table>'}
function renderSummary(){const rows=[];moves().forEach(m=>m.maps.forEach(x=>rows.push(`<tr><td>${esc(m.slot)}</td><td>${esc(x.scenarioId)}</td><td>${x.bothHit}</td><td>${x.gained}</td><td>${x.lost}</td><td>${x.bothMiss}</td><td>${x.notComparable}</td><td>${x.edgeHit?'yes':'no'}</td></tr>`)));summary.innerHTML='<table class=\"summary\"><tr><th>slot</th><th>scenario</th><th>both hit</th><th>gained</th><th>lost</th><th>both miss</th><th>not comparable</th><th>edge hit</th></tr>'+rows.join('')+'</table>'}
function render(){const m=currentMove(),map=currentMap();if(!m||!map)return;panels.innerHTML='';const cols=Math.round((data.grid.maxX-data.grid.minX)/data.grid.step)+1;panels.append(draw('Baseline',map.cells,'baseline',cols),draw('Candidate',map.cells,'candidate',cols),draw('Paired difference',map.cells,'diff',cols));renderTiming(m);renderSummary()}
function init(){const names=data.attackers.map(x=>x.selector);att.innerHTML=names.map(x=>`<option value="${x}">${esc(x)}</option>`).join('');att.onchange=()=>{opt(move,moves(),x=>`${x.slot} ${x.name}`);move.value='0';move.onchange()};move.onchange=()=>{const m=currentMove();scenario.innerHTML=m.maps.map(x=>`<option value="${x.scenarioId}">${esc(x.scenarioId)}</option>`).join('');scenario.value=m.maps[0]?.scenarioId||'';scenario.onchange()};scenario.onchange=render;document.getElementById('meta').innerHTML=`<b>Victim:</b> ${esc(data.victim.displayName)} (${esc(data.victim.identity.packageId)} ${esc(data.victim.identity.version)}) · <b>Grid:</b> ${data.grid.minX}..${data.grid.maxX} X, ${data.grid.minZ}..${data.grid.maxZ} Z, ${data.grid.step}m · <b>Timing:</b> ${data.timing.minPressTick}..${data.timing.maxPressTick} · <b>Targeting:</b> ${esc(data.targetingPolicy)}<br>${data.cautions.map(esc).join(' · ')}`;att.value=names[0];att.onchange()}
init();
""");
        sb.Append("</script></body></html>");
        return sb.ToString();
    }
}
