#nullable enable
using System.Text;
using System.Text.Json;
using System.Text.Encodings.Web;

namespace SlopArena.MoveDataReport;

internal static partial class ContactCoverageHtml
{
    internal static string ToHtml(ContactCoverageReport.NormalCoverageReportData report)
    {
        string json = JsonSerializer.Serialize(report, new JsonSerializerOptions
        {
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            Encoder = JavaScriptEncoder.Default,
            WriteIndented = false,
        });
        var sb = new StringBuilder(64_000);
        sb.Append("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>SlopArena matched normal coverage</title><style>");
        sb.Append("body{font:14px system-ui,sans-serif;margin:20px;color:#17131b;background:#f0eee8;line-height:1.45}h1{font-size:26px;margin:0 0 6px;letter-spacing:-.02em}h2{font-size:18px;margin:26px 0 8px;border-bottom:2px solid #17131b;padding-bottom:5px}.meta{max-width:1000px;color:#24202b}.controls{display:flex;flex-wrap:wrap;gap:12px;margin:16px 0;padding:12px;border:2px solid #17131b;background:#fff}.controls label{display:flex;gap:6px;align-items:center;font-weight:700;min-width:0}.controls select{font:inherit;min-height:36px;min-width:0;padding:5px;border:2px solid #17131b;background:#fff}.controls select:focus,button:focus{outline:3px solid #ffc821;outline-offset:2px}.aerial-only[hidden]{display:none}.legend{display:flex;flex-wrap:wrap;gap:10px;margin:10px 0}.legend span{font-weight:700}.swatch{display:inline-block;width:12px;height:12px;border:1px solid #17131b;margin-right:3px;vertical-align:-1px}.layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(280px,360px);gap:18px;align-items:start}main,.panel{min-width:0}.scroll,.comparison,.summary{overflow:auto;border:2px solid #17131b;background:#fff}.grid{border-collapse:collapse;min-width:420px;width:100%}.grid th,.grid td{border:1px solid #625c6b;padding:5px;text-align:center;white-space:nowrap}.grid th{background:#24202b;color:#f0eee8;position:sticky;top:0;z-index:1}.grid th:first-child{left:0;z-index:2}.grid .row-label{background:#24202b;color:#f0eee8;position:sticky;left:0;z-index:1}.cell{font:700 12px system-ui,sans-serif;border:1px solid #17131b;min-width:74px;min-height:44px;padding:8px 5px;cursor:pointer;color:#17131b}.cell:hover{filter:brightness(1.05)}.cell.selected{box-shadow:inset 0 0 0 3px #17131b}.panel{border:2px solid #17131b;background:#fff;padding:12px}.panel h3{margin:0 0 7px;font-size:16px}.detail{white-space:pre-wrap;min-height:120px;font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:12px;background:#24202b;color:#f0eee8;padding:10px;overflow:auto}.comparison button,.extra button{font:inherit;text-align:left;background:#fff;border:0;padding:7px;width:100%;cursor:pointer}.comparison button:hover,.extra button:hover{background:#ffc821}.comparison table,.extra table,.summary table{border-collapse:collapse;width:100%;background:#fff}.comparison td,.comparison th,.extra td,.extra th,.summary td,.summary th{border:1px solid #625c6b;padding:6px;text-align:left}.comparison th,.extra th,.summary th{background:#24202b;color:#f0eee8}.outcome{font-weight:800}.small{font-size:12px;color:#24202b}.note{padding:8px;border:1px solid #625c6b;background:#fff}.summary table{min-width:660px}.cautions{padding-left:20px}@media(max-width:760px){body{margin:12px}.layout{grid-template-columns:1fr}.panel{padding:8px}.controls{align-items:stretch}.controls label{width:100%;justify-content:space-between}.controls select{max-width:62%}}");
        sb.Append(".cell.hit{background:#4cdd88}.cell.miss{background:#fff}.cell.unavailable{background:#d7d1dc}.cell.truncated{background:#e05c2a}");
        sb.Append(".swatch.hit{background:#4cdd88}.swatch.miss{background:#fff}.swatch.unavailable{background:#d7d1dc}.swatch.truncated{background:#e05c2a}");
        sb.Append("</style></head><body><h1>Matched normal coverage</h1><div id=\"meta\" class=\"meta\"></div><div class=\"controls\"><label>Attacker <select id=\"attacker\" disabled></select></label><label>Canonical normal <select id=\"move\"></select></label><label>Starting height <select id=\"height\"></select></label><label id=\"styleLabel\" class=\"aerial-only\" hidden>Jump style <select id=\"style\"></select></label><label id=\"checkpointLabel\" class=\"aerial-only\" hidden>Checkpoint <select id=\"checkpoint\"></select></label></div><div class=\"legend\"><span><i class=\"swatch hit\"></i>Hit</span><span><i class=\"swatch miss\"></i>Miss</span><span><i class=\"swatch unavailable\"></i>Unavailable</span><span><i class=\"swatch truncated\"></i>Truncated</span></div><div class=\"layout\"><main><h2>Sampled X/Z positions</h2><div id=\"gridNote\" class=\"small\"></div><div id=\"grid\" class=\"scroll\"></div><h2>Extra positions</h2><div id=\"extraNote\" class=\"small\"></div><div id=\"extras\" class=\"scroll\"></div><h2>Matching-normal comparison</h2><div id=\"comparison\" class=\"comparison\"></div><h2>Sampled coverage summary</h2><div id=\"summary\" class=\"summary\"></div></main><aside class=\"panel\"><h2>Selected sample</h2><div id=\"detail\" class=\"detail\">Select a position.</div><h2>Jump references</h2><div id=\"references\"></div><h2>Cautions</h2><ul id=\"cautions\" class=\"cautions\"></ul></aside></div><script id=\"coverage-data\" type=\"application/json\">");
        sb.Append(json);
        sb.Append("</script><script>");
        sb.Append(@"
const data=JSON.parse(document.getElementById('coverage-data').textContent);
const attacker=document.getElementById('attacker'),move=document.getElementById('move'),height=document.getElementById('height'),style=document.getElementById('style'),checkpoint=document.getElementById('checkpoint');
const styleLabel=document.getElementById('styleLabel'),checkpointLabel=document.getElementById('checkpointLabel'),grid=document.getElementById('grid'),gridNote=document.getElementById('gridNote'),extras=document.getElementById('extras'),extraNote=document.getElementById('extraNote'),comparison=document.getElementById('comparison'),summary=document.getElementById('summary'),detail=document.getElementById('detail'),references=document.getElementById('references');
let selectedPositionIndex=null;
const esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const fmt=n=>n==null?'not observed / not applicable':(typeof n==='number'?Number(n).toFixed(3):String(n));
const currentMove=()=>data.moves[+move.value]||data.moves[0];
const currentHeight=()=>Number(height.value);
const isAir=()=>!!currentMove()?.isAirborne;
const sampleFor=(m,p)=>data.samples.find(s=>s.slotId===m.slotId&&s.positionIndex===p.index&&(!isAir()?(s.jumpStyle==null&&s.checkpoint==null):(s.jumpStyle===style.value&&s.checkpoint===checkpoint.value)));
const state=s=>s?`feet=(${fmt(s.positionX)},${fmt(s.positionY)},${fmt(s.positionZ)}) centerY=${fmt(s.capsuleCenterY)} vel=(${fmt(s.velocityX)},${fmt(s.velocityY)},${fmt(s.velocityZ)}) grounded=${s.isGrounded} state=${s.actionState} facing=${fmt(s.facingYawDegrees)}°`:'not observed / not applicable';
function setOptions(sel,values,label){sel.textContent='';values.forEach((v,i)=>{const o=document.createElement('option');o.value=String(v.value??i);o.textContent=label(v);sel.append(o)})}
function renderSelects(){
 const oldHeight=currentHeight();setOptions(move,data.moves.map((m,i)=>({value:i,text:`${m.slotId} · ${m.name}`})),x=>x.text);move.value=String(Math.max(0,Math.min(data.moves.length-1,+move.value||0)));
 const heights=[...new Set(data.positions.map(p=>p.y))].sort((a,b)=>a-b);setOptions(height,heights.map(x=>({value:x,text:`Y ${x}`})),x=>x.text);height.value=heights.includes(oldHeight)?String(oldHeight):String(heights[0]);
 setOptions(style,['neutral','neutral-drift','running'].map(x=>({value:x,text:x})),x=>x.text);setOptions(checkpoint,['immediate','early','late'].map(x=>({value:x,text:x})),x=>x.text);
}
function visibleSample(p){return sampleFor(currentMove(),p)}
function outcomeCell(s){const b=document.createElement('button');b.className=`cell ${s?.outcome||'unavailable'}`;b.type='button';b.textContent=s?.outcome==='hit'?'Hit':s?.outcome==='miss'?'Miss':s?.outcome==='truncated'?'Truncated':'Unavailable';b.title=`${b.textContent}; position index ${s?.positionIndex??'—'}`;b.onclick=()=>show(s);return b}
function renderGrid(){
 const m=currentMove(),ps=data.positions.filter(p=>p.y===currentHeight()&&!p.isExtra).sort((a,b)=>b.z-a.z||a.x-b.x);const xs=[...new Set(ps.map(p=>p.x))].sort((a,b)=>a-b);grid.textContent='';gridNote.textContent=ps.length?`Rows descend in Z; columns ascend in X. +Z is forward. Height Y=${currentHeight()} is target feet elevation at the reference instant.`:'No Cartesian-grid positions at this height; use the extra-position table below.';
 if(!ps.length)return;const t=document.createElement('table');t.className='grid';const h=document.createElement('tr');const corner=document.createElement('th');corner.textContent='Z \\ X';h.append(corner);xs.forEach(x=>{const th=document.createElement('th');th.textContent=`X ${x}`;h.append(th)});t.append(h);[...new Set(ps.map(p=>p.z))].sort((a,b)=>b-a).forEach(z=>{const tr=document.createElement('tr'),th=document.createElement('th');th.className='row-label';th.textContent=`Z ${z}`;tr.append(th);xs.forEach(x=>{const td=document.createElement('td'),p=ps.find(q=>q.x===x&&q.z===z);if(p)td.append(outcomeCell(visibleSample(p)));else td.textContent='—';tr.append(td)});t.append(tr)});grid.append(t)
}
function renderExtras(){const ps=data.positions.filter(p=>p.y===currentHeight()&&p.isExtra);extraNote.textContent=ps.length?`Extra positions at Y=${currentHeight()}. They use the same reference and detail view.`:'No extra positions at this height.';extras.textContent='';if(!ps.length)return;const t=document.createElement('table');t.className='extra';const h=document.createElement('tr');['XYZ','Outcome','Open'].forEach(x=>{const th=document.createElement('th');th.textContent=x;h.append(th)});t.append(h);ps.forEach(p=>{const s=visibleSample(p),tr=document.createElement('tr');const xyz=document.createElement('td');xyz.textContent=`(${p.x}, ${p.y}, ${p.z})`;const out=document.createElement('td');out.textContent=s?.outcome||'unavailable';out.className=`outcome ${s?.outcome||'unavailable'}`;const action=document.createElement('td');action.append(outcomeCell(s));tr.append(xyz,out,action);t.append(tr)});extras.append(t)}
function show(s){if(!s){selectedPositionIndex=null;detail.textContent='not observed / not applicable';renderComparison();return}selectedPositionIndex=s.positionIndex;const lines=[`Outcome: ${s.outcome} (${s.reason||'no additional reason'})`,`Slot: ${s.slotId}; position index: ${s.positionIndex}; scheduled press: ${fmt(s.scheduledPressTick)}; actual press: ${fmt(s.actualPressTick)}`,`Attack input sent: ${s.attackInputSent}; activation: ${fmt(s.activationId)}; wire slot: ${fmt(s.wireSlot)}; airborne at start: ${fmt(s.airborneAtStart)}`,`Reference: ${fmt(s.referenceId)} at tick ${fmt(s.referenceTick)}; observed phase: ${fmt(s.observedPressPhase)}`,`Initial overlap: ${s.initialBodyOverlap}; reference relative: ${s.referenceTargetMinusAttacker?`(${fmt(s.referenceTargetMinusAttacker.x)}, ${fmt(s.referenceTargetMinusAttacker.y)}, ${fmt(s.referenceTargetMinusAttacker.z)})`:'not observed / not applicable'}`,`Pre-press attacker: ${state(s.prePressAttacker)}`,`Pre-press victim: ${state(s.prePressVictim)}`,`Contact: ${s.firstContact?`tick ${s.firstContact.tick}, damage ${fmt(s.firstContact.damage)}, delay ${s.firstContact.ticksAfterPress}`:'not observed / not applicable'}`,`Contact relative: ${s.firstContactRelative?`(${fmt(s.firstContactRelative.x)}, ${fmt(s.firstContactRelative.y)}, ${fmt(s.firstContactRelative.z)})`:'not observed / not applicable'}`,`Landing: tick ${fmt(s.firstLandingTick)}; before press=${s.landedBeforePress}; before contact=${s.landedBeforeContact}; contact on landing=${s.contactOnLandingTick}`,`Damage: ${fmt(s.targetDamageBefore)} → ${fmt(s.targetDamageAfter)}; completion: tick ${fmt(s.completionTick)} (${fmt(s.completionReason)})`,`Final attacker: ${state(s.finalAttacker)}`,`Final victim: ${state(s.finalVictim)}`];detail.textContent=lines.join('\n');renderComparison()}
function renderComparison(){const p=data.positions.find(x=>x.index===selectedPositionIndex&&x.y===currentHeight())||data.positions.find(x=>x.y===currentHeight()&&!x.isExtra)||data.positions.find(x=>x.y===currentHeight());comparison.textContent='';if(!p){comparison.textContent='No position at this height.';return}const rows=data.moves.filter(m=>m.isAirborne===isAir()).map(m=>({m,s:sampleFor(m,p)}));const t=document.createElement('table');const h=document.createElement('tr');['Normal','Outcome','Reason'].forEach(x=>{const th=document.createElement('th');th.textContent=x;h.append(th)});t.append(h);rows.forEach(({m,s})=>{const tr=document.createElement('tr'),a=document.createElement('td'),b=document.createElement('td'),c=document.createElement('td'),button=document.createElement('button');button.textContent=`${m.slotId} · ${m.name}`;button.onclick=()=>show(s);a.append(button);b.textContent=s?.outcome||'unavailable';b.className=`outcome ${s?.outcome||'unavailable'}`;c.textContent=s?.reason||'—';tr.append(a,b,c);t.append(tr)});comparison.append(t);if(!rows.some(x=>x.s?.outcome==='hit')){const n=document.createElement('div');n.className='note';n.textContent='No selected normal connected at this sampled condition. Unavailable and truncated rows remain counted.';comparison.append(n)}}
function renderSummary(){const m=currentMove();const rows=data.summaries.filter(x=>x.slotId===m.slotId&&x.startingY===currentHeight()&&(!isAir()?(x.jumpStyle==null&&x.checkpoint==null):(x.jumpStyle===style.value&&x.checkpoint===checkpoint.value)));summary.textContent='';const t=document.createElement('table');const h=document.createElement('tr');['Normal','Hits','Misses','Unavailable','Truncated','Hits / completed','Fraction'].forEach(x=>{const th=document.createElement('th');th.textContent=x;h.append(th)});t.append(h);rows.forEach(x=>{const tr=document.createElement('tr');[x.slotId,x.hits,x.misses,x.unavailable,x.truncated,`${x.hits} / ${x.completedAttempts}`,x.connectionFraction==null?'not applicable':x.connectionFraction.toFixed(3)].forEach((v,i)=>{const td=document.createElement('td');td.textContent=String(v);if(i===1)td.className='outcome';tr.append(td)});t.append(tr)});summary.append(t)}
function renderReferences(){references.textContent='';const refs=data.jumpReferences.filter(r=>!isAir()||r.jumpStyle===style.value);refs.forEach(r=>{const p=document.createElement('p');p.textContent=`${r.jumpStyle}: takeoff ${r.takeoffTick}, apex ${r.apexTick}, landing ${r.landingTick}, flight ${r.flightTicks}; checkpoints ${r.checkpoints.map(x=>`${x.label}=${x.absoluteTick}`).join(', ')}`;references.append(p)});if(!refs.length)references.textContent='Ground normals use the initial grounded state as reference.'}
function render(){const air=isAir();styleLabel.hidden=!air;checkpointLabel.hidden=!air;style.disabled=!air;checkpoint.disabled=!air;renderGrid();renderExtras();renderComparison();renderSummary();renderReferences()}
function init(){attacker.textContent='';const ao=document.createElement('option');ao.textContent=`${data.attacker.selector} · ${data.attacker.displayName}`;attacker.append(ao);document.getElementById('meta').textContent=`${data.attacker.displayName} vs ${data.victim.displayName} · ${data.attacker.identity.packageId} ${data.attacker.identity.version} · ${data.positions.length} positions · ${data.samples.length} samples · 60 Hz. Coordinates are target minus attacker at the matched reference; elevated targets fall after registration.`;data.cautions.forEach(x=>{const li=document.createElement('li');li.textContent=x;document.getElementById('cautions').append(li)});renderSelects();const refresh=()=>{selectedPositionIndex=null;detail.textContent='Select a position.';render()};move.onchange=refresh;height.onchange=refresh;style.onchange=refresh;checkpoint.onchange=refresh;render()}
init();
");
        sb.Append("</script></body></html>");
        return sb.ToString();
    }
}
