// PROTOTYPE — throwaway trajectory sweep for wayfinder ticket #141
// (Flight model feel prototype: trajectory sweep). NOT production code.
// Regenerates docs/research/flight-model-sweep.md from the models below.
//
// Model (a) "current" mirrors src/Shared/Simulation.cs exactly:
//   - launch: ApplyKnockback (:1092) — mag = base + growth*(damage/100),
//     KV = mag*cos(angle) horizontal, mag*sin(angle) vertical
//   - hitstun: clamp(8 + (int)(mag*0.5), 8, 60) capped by StunTicks (:1118)
//   - in-flight: KV *= exp(-1.8*dt) all axes (ProcessHitstun :614, ProcessKnockback :735)
//   - gravity: KnockbackMinGravity = 2.0 m/s² (:49)
// Model (b) "optionA" — Melee-shaped: constant KV through hitstun, full gravity
//   does the vertical work, linear horizontal friction (10 m/s²) after hitstun.
// Model (c) "optionB" — hybrid: linear (constant m/s²) horizontal decay instead
//   of exponential, min gravity kept.
//
// All sweeps launch along +Z from ground height 0, 60 Hz ticks, flight ends on
// landing (y <= 0) or after 600 ticks (10 s cap). Blast zones are stage-specific
// and NOT modeled — this sweep shows trajectory shape + flight metrics only.

using System.Text;

class Program
{
    const float TickDt = 1f / 60f;
    const float ExpLambda = 1.8f;       // Simulation.cs KnockbackDecayRate
    const float MinGravity = 2.0f;      // Simulation.cs KnockbackMinGravity
    const float FullGravity = 36f;      // FightGuy/Kistu stats.Gravity (gravity "doing the work")
    const float LinearDecel = 10f;      // m/s², within research doc's suggested 5-15
    const float DeadZone = 0.015f;      // Simulation.cs VelocityDeadZone
    const int MaxTicks = 600;

    const int PlotW = 72, PlotH = 18;

    enum Model { Current, OptionA, OptionB }

    readonly record struct Launch(float Mag, float KvH, float KvY, int HitstunTicks);

    readonly record struct Flight(float[] H, float[] Y, int HitstunEndIdx, int Ticks, float MaxHeight)
    {
        public float HdistAtHitstunEnd => HitstunEndIdx >= 0 ? H[HitstunEndIdx] : 0f;
        public float TotalHdist => H[^1];
        public float FlightSeconds => (Ticks - 1) * TickDt;
        public bool Capped => Ticks >= MaxTicks;
    }

    static void Main()
    {
        var moves = new[]
        {
            ("Light jab", (sbyte)15, 2f, 1.5f, (ushort)20),
            ("Mid launcher", (sbyte)25, 8f, 4f, (ushort)24),
            ("Kill move", (sbyte)20, 18f, 10f, (ushort)24),
        };
        int[] percents = { 0, 50, 150 };
        Model[] models = { Model.Current, Model.OptionA, Model.OptionB };
        string[] modelNames = { "(a) current exp decay", "(b) Option A — constant + linear friction", "(c) Option B — linear decay" };
        char[] modelChars = { 'a', 'b', 'c' };

        var sb = new StringBuilder();
        sb.AppendLine("# Flight Model Feel — Trajectory Sweep");
        sb.AppendLine();
        sb.AppendLine("> Prototype artifact for [Flight model feel prototype: trajectory sweep](https://github.com/Binoui/SlopArena/issues/141).");
        sb.AppendLine("> The artifact [*Flight model: Melee-shaped vs hybrid*](https://github.com/Binoui/SlopArena/issues/130) reacts to.");
        sb.AppendLine("> Generated by `dotnet run --project research/flight-sweep` (throwaway code, not production).");
        sb.AppendLine();
        sb.AppendLine("## Method");
        sb.AppendLine();
        sb.AppendLine("- 60 Hz ticks (`TickDt = 1/60`), launch along +Z from ground height 0; flight ends at landing (`Y <= 0`) or the 10 s cap (600 ticks).");
        sb.AppendLine("- Launch magnitude: `base + growth × (damage% / 100)` — the current `ApplyKnockback` formula (Simulation.cs:1097). Angle per profile (`KnockbackProfile.cs`).");
        sb.AppendLine("- Hitstun: `clamp(8 + (int)(mag × 0.5), 8, 60)` capped by the move's `StunTicks` (Simulation.cs:1118) — identical across models, since it is computed at connect from the launch magnitude.");
        sb.AppendLine("- Blast zones are stage-specific and **not** modeled: the sweep shows trajectory shape and flight metrics, not kill power.");
        sb.AppendLine();
        sb.AppendLine("### Models");
        sb.AppendLine();
        sb.AppendLine("| Model | During hitstun | After hitstun (tumble) | Vertical gravity |");
        sb.AppendLine("|---|---|---|---|");
        sb.AppendLine("| (a) current | `KV *= exp(-1.8·dt)` all axes | same decay | 2.0 m/s² (`KnockbackMinGravity`) |");
        sb.AppendLine("| (b) Option A (Melee-shaped) | **constant KV** | linear friction 10 m/s² on horizontal, azimuth-preserving | 36 m/s² full (does the vertical work) |");
        sb.AppendLine("| (c) Option B (hybrid) | linear decay 10 m/s² per axis (constant rate) | same linear decay | 2.0 m/s² (min, kept) |");
        sb.AppendLine();
        sb.AppendLine("Gravity/friction constants are the tunables under discussion in #130; 10 m/s² sits in the middle of the research doc's suggested 5–15 range.");
        sb.AppendLine();

        foreach (var (name, angle, baseKB, growth, stun) in moves)
        {
            sb.AppendLine($"## {name} — {angle}°, base {baseKB}, growth {growth}, StunTicks {stun}");
            sb.AppendLine();

            foreach (int pct in percents)
            {
                var launch = LaunchMove(angle, baseKB, growth, stun, pct);
                var flights = models.Select(m => Simulate(launch, m)).ToArray();

                sb.AppendLine($"### {name} @ {pct}% (mag {launch.Mag:F1}, hitstun {launch.HitstunTicks} ticks = {launch.HitstunTicks * TickDt:F2} s)");
                sb.AppendLine();
                sb.AppendLine("| Model | Flight time | Max height | Hdist at hitstun end | Total hdist |");
                sb.AppendLine("|---|---|---|---|---|");
                for (int i = 0; i < models.Length; i++)
                {
                    var f = flights[i];
                    sb.Append($"| {modelNames[i]} | {f.FlightSeconds:F2} s{(f.Capped ? " (capped)" : "")} | {f.MaxHeight:F2} m | {f.HdistAtHitstunEnd:F2} m | {f.TotalHdist:F2} m |");
                    sb.AppendLine();
                }
                sb.AppendLine();
                sb.AppendLine("```");
                sb.AppendLine(Plot(flights));
                sb.AppendLine("```");
                sb.AppendLine();
                sb.AppendLine($"Legend: `{modelChars[0]}` = current, `{modelChars[1]}` = Option A, `{modelChars[2]}` = Option B. Uppercase = position at hitstun end. X = horizontal distance (m), Y = height (m).");
                sb.AppendLine();
            }
        }

        // Gravity coupling: Option A collapses at current KB scale + full gravity.
        sb.AppendLine("## Gravity coupling (why Option A collapses at current launch scale)");
        sb.AppendLine();
        sb.AppendLine("Option A pairs a *constant* KV with full gravity (36 m/s²). At today's launch magnitudes (kill move @ 150% = mag 33) the vertical component is `33·sin(20°) = 11.3 m/s` — full gravity eats that in ~0.6 s, so the victim bounces almost immediately. The Melee feel only emerges when launch scale and gravity are rebalanced *together*. Sweep of the kill move @ 150% across flight gravities for Option A (friction fixed at 10 m/s²):");
        sb.AppendLine();
        sb.AppendLine("| Flight gravity (m/s²) | Flight time | Max height | Hdist at hitstun end | Total hdist |");
        sb.AppendLine("|---|---|---|---|---|");
        foreach (float g in new[] { 2f, 8f, 24f, 36f })
        {
            var launchKill = LaunchMove(20f, 18f, 10f, 24, 150);
            var f = SimulateGravity(launchKill, g);
            sb.Append($"| {g:F0} | {f.FlightSeconds:F2} s{(f.Capped ? " (capped)" : "")} | {f.MaxHeight:F2} m | {f.HdistAtHitstunEnd:F2} m | {f.TotalHdist:F2} m |");
            sb.AppendLine();
        }
        sb.AppendLine();
        sb.AppendLine("At 8 m/s² (roughly a quarter of full) Option A produces Melee-like arcs at the current launch scale; 36 m/s² is unplayable without a KB-scale retune (that retune is ticket #132's business).");

        sb.AppendLine();
        sb.AppendLine("## Reading the sweep");
        sb.AppendLine();
        sb.AppendLine("- **Current (a)** front-loads travel: most horizontal distance accrues in the first ~0.5 s, then an asymptotically dead tail — the flight path is a flattened arc. The all-axis exponential decay is what keeps the vertical in check (KVY shrinks every tick).");
        sb.AppendLine("- **Option A (b)** holds launch speed through hitstun, so the *hitstun-end* distance is much larger; the arc is gravity-dominated (taller at low %, lower-and-longer at high %) **provided flight gravity is rebalanced down** (see coupling table). At current gravity (36) and current KB magnitudes it produces almost no flight.");
        sb.AppendLine("- **Option B (c), per-axis linear** — the direct analog of the current per-axis exponential — has a **hover artifact**: at the apex the sign-preserving linear decay starts counteracting min gravity (KVY oscillates near 0), so launcher/kill victims never land within the 10 s cap. The all-axis decay shape does *not* survive the switch from multiplicative to additive. The alternative reading — decay horizontal only, let min gravity own the vertical — gives runaway vertical (31 m arc on the kill move) because 2.0 m/s² cannot tame a 33 m/s launch without KVY decay.");
        sb.AppendLine("- Compare the `Hdist at hitstun end` column across models — that is the distance a combo follow-up must cover to reach the victim while they are still in hitstun.");
        sb.AppendLine();
        sb.AppendLine("## What this says for #130");
        sb.AppendLine();
        sb.AppendLine("- The current model's all-axis exponential decay is load-bearing on the **vertical**: it is the only thing keeping arcs low at 2.0 m/s² gravity. Any replacement must either keep a vertical decay, or raise gravity (Option A's wager), or rebalance KB magnitudes.");
        sb.AppendLine("- Option A is viable only as a *package*: constant KV + gravity rebalance (~8 m/s² per the coupling table) + optional KB-scale retune (#132). Its pitch — combo-relevant hitstun-end distances, Melee-like arcs — shows up clearly in the `Hdist at hitstun end` column (e.g. kill @ 150%: 12.4 m vs 8.7 m current).");
        sb.AppendLine("- Option B as a *pure* linear swap is not viable without extra machinery (dead-zone on the vertical, or a distinct vertical law) — the hover artifact is structural, not a tuning miss.");

        File.WriteAllText("docs/research/flight-model-sweep.md", sb.ToString());

        // Console summary for the session log
        foreach (var (name, angle, baseKB, growth, stun) in moves)
        {
            Console.WriteLine($"== {name} ==");
            foreach (int pct in percents)
            {
                var launch = LaunchMove(angle, baseKB, growth, stun, pct);
                var flights = models.Select(m => Simulate(launch, m)).ToArray();
                Console.WriteLine($"  {pct}%: mag={launch.Mag:F1} hs={launch.HitstunTicks}t | " +
                    string.Join(" | ", flights.Select((f, i) =>
                        $"{modelChars[i]}: flight={f.FlightSeconds:F2}s maxH={f.MaxHeight:F2}m hsEnd={f.HdistAtHitstunEnd:F2}m total={f.TotalHdist:F2}m")));
            }
        }
    }

    static Launch LaunchMove(float angleDeg, float baseKB, float growthKB, ushort stunTicks, int damagePct)
    {
        float mag = baseKB + growthKB * (damagePct * 0.01f);          // Simulation.cs:1097
        float rad = angleDeg * MathF.PI / 180f;
        float kvH = mag * MathF.Cos(rad);
        float kvY = mag * MathF.Sin(rad);
        int hitstun = stunTicks > 0 && mag > 0.5f
            ? Math.Min(Math.Clamp(8 + (int)(mag * 0.5f), 8, 60), stunTicks)
            : 0;
        return new Launch(mag, kvH, kvY, hitstun);
    }

    static Flight Simulate(in Launch l, Model model)
    {
        var h = new List<float> { 0f };
        var y = new List<float> { 0f };
        float kvH = l.KvH, kvY = l.KvY;
        int hs = l.HitstunTicks;
        int hsEndIdx = -1;
        int t;
        for (t = 1; t <= MaxTicks; t++)
        {
            bool inHitstun = hs > 0;
            if (inHitstun) hs--;

            switch (model)
            {
                case Model.Current:
                {
                    float decay = MathF.Exp(-ExpLambda * TickDt);
                    kvH *= decay;
                    kvY *= decay;
                    kvY -= MinGravity * TickDt;
                    break;
                }
                case Model.OptionA:
                {
                    // Constant KV through hitstun; full gravity does vertical work.
                    if (!inHitstun)
                    {
                        // Tumble: linear horizontal friction along the launch azimuth.
                        float reduction = MathF.Min(MathF.Abs(kvH), LinearDecel * TickDt);
                        kvH -= MathF.CopySign(reduction, kvH);
                    }
                    kvY -= FullGravity * TickDt;
                    if (MathF.Abs(kvH) < DeadZone) kvH = 0f;
                    break;
                }
                case Model.OptionB:
                {
                    // Linear (constant m/s²) decay per axis — the direct analog of
                    // the current per-axis exponential (each axis decelerates at a
                    // constant rate instead of proportionally), hard stop at v/decel.
                    float hReduction = MathF.Min(MathF.Abs(kvH), LinearDecel * TickDt);
                    kvH -= MathF.CopySign(hReduction, kvH);
                    float yReduction = MathF.Min(MathF.Abs(kvY), LinearDecel * TickDt);
                    kvY -= MathF.CopySign(yReduction, kvY);
                    kvY -= MinGravity * TickDt;
                    if (MathF.Abs(kvH) < DeadZone) kvH = 0f;
                    break;
                }
            }

            float nextH = h[^1] + kvH * TickDt;
            float nextY = y[^1] + kvY * TickDt;
            if (hsEndIdx < 0 && hs == 0) hsEndIdx = h.Count; // index of first post-hitstun sample
            h.Add(nextH);
            y.Add(nextY);
            if (nextY <= 0f) { t++; break; } // landed — flight over
        }
        float maxH = 0f;
        foreach (float v in y) if (v > maxH) maxH = v;
        return new Flight(h.ToArray(), y.ToArray(), hsEndIdx, t, maxH);
    }

    // Option A physics with a parameterized flight gravity (coupling table).
    static Flight SimulateGravity(in Launch l, float gravity)
    {
        var h = new List<float> { 0f };
        var y = new List<float> { 0f };
        float kvH = l.KvH, kvY = l.KvY;
        int hs = l.HitstunTicks;
        int hsEndIdx = -1;
        int t;
        for (t = 1; t <= MaxTicks; t++)
        {
            bool inHitstun = hs > 0;
            if (inHitstun) hs--;
            if (!inHitstun)
            {
                float reduction = MathF.Min(MathF.Abs(kvH), LinearDecel * TickDt);
                kvH -= MathF.CopySign(reduction, kvH);
            }
            kvY -= gravity * TickDt;
            if (MathF.Abs(kvH) < DeadZone) kvH = 0f;

            float nextH = h[^1] + kvH * TickDt;
            float nextY = y[^1] + kvY * TickDt;
            if (hsEndIdx < 0 && hs == 0) hsEndIdx = h.Count;
            h.Add(nextH);
            y.Add(nextY);
            if (nextY <= 0f) { t++; break; }
        }
        float maxH = 0f;
        foreach (float v in y) if (v > maxH) maxH = v;
        return new Flight(h.ToArray(), y.ToArray(), hsEndIdx, t, maxH);
    }

    // ── ASCII plot: all three trajectories overlaid, uppercase marks hitstun end ──
    static string Plot(Flight[] flights)
    {
        float maxH = flights.Max(f => f.MaxHeight);
        float maxDist = flights.Max(f => f.TotalHdist);
        if (maxH <= 0f) maxH = 0.1f;
        if (maxDist <= 0f) maxDist = 1f;
        var grid = new char[PlotH, PlotW];
        for (int r = 0; r < PlotH; r++)
            for (int c = 0; c < PlotW; c++)
                grid[r, c] = '.';

        void Draw(int i, char ch)
        {
            var f = flights[i];
            for (int idx = 0; idx < f.H.Length; idx++)
            {
                int c = (int)Math.Clamp(f.H[idx] / maxDist * (PlotW - 1), 0, PlotW - 1);
                int r = (int)Math.Clamp(f.Y[idx] / maxH * (PlotH - 1), 0, PlotH - 1);
                r = PlotH - 1 - r;
                bool isHsEnd = idx == f.HitstunEndIdx;
                if (isHsEnd)
                    grid[r, c] = char.ToUpperInvariant(ch);
                else if (grid[r, c] == '.')
                    grid[r, c] = ch;
            }
        }

        Draw(0, 'a');
        Draw(1, 'b');
        Draw(2, 'c');

        var lines = new List<string> { $"Y {maxH:F1}m" };
        for (int r = 0; r < PlotH; r++)
        {
            var row = new char[PlotW];
            for (int c = 0; c < PlotW; c++) row[c] = grid[r, c];
            lines.Add(new string(row));
        }
        lines.Add($"0 +{new string('─', PlotW - 2)}+ {maxDist:F1}m  X");
        return string.Join('\n', lines);
    }
}
